version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/ts'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'ansi-styles' # Later versions switch to ESM
      - dependency-name: 'ansi-escapes' # Later versions switch to ESM
